CREATE TABLE IF NOT EXISTS aida.auditoria (
    id SERIAL PRIMARY KEY,
    usuario_id INTEGER REFERENCES aida.usuarios(id) ON DELETE SET NULL,
    accion VARCHAR(100) NOT NULL,
    detalle TEXT,
    fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
